version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
  - ps: Install-Product node $env:nodejs_version x64
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./JournalApp/JournalApp.csproj --verbosity m
  - cmd: npm install ./JournalApp/ClientApp
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./CribbageBot/CribbageBot.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\JournalApp\bin\Debug\netcoreapp2.0\publish'
   name: Website
   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  # Commented out because test scripts don't actually exist.
#  - cmd: dotnet restore ./tests/tests.csproj --verbosity m
#  # run the unit tests (requires changing into the test directory)
#  - cmd: cd tests
#  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy:
- provider: Environment
  name: JournalAppWebDeployENV
  on:
    branch: master
